config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get 'recipes/index'
  devise_for :users


  # Homepage
  root to: "pages#home"

  # current_user.clinician? == true ? root to: "pages#clinician_dashboard" :  root to: "pages#home"


  # Meals/Recipe page
  get '/meals/breakfast', to: 'meals#breakfast', as: 'breakfast'
  get '/meals/lunch', to: 'meals#lunch', as: 'lunch'
  get '/meals/snacks', to: 'meals#snacks', as: 'snacks'
  get '/meals/dinner', to: 'meals#dinner', as: 'dinner'
  resources :meals, only: [:index, :show]

   # get '/meals/:id', to: 'meals#show', as: 'meal'




  # User Dashboard
  resources :recordings
  get "dashboard", to: "pages#dashboard"

  # Clinician Dashboard
  get 'clinician_dashboard', to: 'pages#clinician_dashboard'
  get 'dashboard/patients/:id', to: 'pages#show', as: :patient_profile
  # get 'dashboard/patients/:id/chatroom', to: 'pages#show' , as: :chatroom

  get 'recordings/:id/feedback', to: 'recordings#feedback', as: :feedback
  # May get deleted as it gets moved to the dashboard
  get 'recordings/:id', to: 'recordings#new'
  post 'recordings/:id', to: 'recordings#create'
  get 'recordings/:id', to: 'recordings#edit'
  # get 'recordings', to: 'recordings#index', as: :search # This is for the searchbar - get request for items (bloods and meals) that match a certain condition (i.e. the date user input)
  # get 'recordings/:id/edit', to: 'recordings#edit' # Edit your blood glucose entry if user had made a mistake
  patch 'recordings/:id', to: 'recordings#update' # Update your entry, given your details that were previously there( present in the form), to change
  delete 'recordings/:id', to: 'recordings#destroy' # Delete your BM entry


  # Chatroom
  # get 'chatroom/:consultation_id', to: 'chatrooms#index'
  resources :chatrooms, only: [:show] do
    resources :messages , only: [:create]
  end

  # resources :users do
  #   post 'create_chat', on: :member
  #   resources :chatrooms, only: [:index, :show] do
  #     resources :messages, only: [:create]
  #   end
  # end





end

app/models/recording.rb
class Recording < ApplicationRecord
  belongs_to :user
  has_many :results
  has_many :meals, through: :results
  validates :reading, presence: true
  validates :date, presence: true
  validates :time, presence: true
  # format :/(0[1-9]|[12][0-9]|3[01])[- /.](0[1-9]|1[012])[- /.](19|20)\d\d/

  THRESHOLDS_UPPER_BOUND = 7.7
  THRESHOLDS_LOWER_BOUND = 4.0

end

app/controllers/recordings_controller.rb
class RecordingsController < ApplicationController

  def index
    @user = params[:patient].present? ? User.find(params[:patient])  : current_user
    @recordings = @user.recordings.order(date: :desc)
    @meal_recordings = @user.recordings.order(date: :desc).where.not(ingredients: "")
    @blood_glucose_recordings = @user.recordings.order(date: :desc).where(ingredients: "").or(@recordings.where.not(ingredients: ""))
    @searches = @blood_glucose_recordings.where(date: params[:query])
    @patients = User.where(clinician: false)

  end

  def show
    @recording = Recording.find(params[:id])
    @recording.destroy
    redirect_to recordings_path, status: :see_other
  end



  def feedback
    # @reading = Recording.find(params[:id]).reading
    @reading = Recording.find(params[:id]).reading
    @timing_above = Meal.all.where(threshold: "above").group_by(&:timing).transform_values(&:first).values
    @timing_below = Meal.all.where(threshold: "below").group_by(&:timing).transform_values(&:first).values
  end

  def new
    @recording = Recording.new
  end

  def edit
    @recording = Recording.find(params[:id])
  end

  def update
    @recording = Recording.find(params[:id])
    @recording.update(recording_params)
    redirect_to recordings_path
  end

  def create
    @recording = Recording.new(recording_params)
    @recording.user = current_user
    if @recording.save
       # After submitting the form , details are submitted to index with all the BM and meal submissions of the last wek
      redirect_to feedback_path(@recording)
    else
      render :new, status: :unprocessable_entity
    end
    #Also redirected to the fedback page - personalised writing # Ruby if else logic will be in the html itself
  end

  def destroy
    @recording = Recording.find(params[:id])
    @recording.destroy
    redirect_to recordings_path, status: :see_other
  end




  private
  def recording_params
    params.require(:recording).permit(:reading, :date, :time, :ingredients)
  end

end

app/views/recordings/_recomendation.html.erb
<div class="meal-index-card">
  <h1>Our suggestions:</h1>
  <div class="meal-cards-container">
    <% timing.each do |meal| %>
      <%= link_to meal_path(meal) do %>
         <div class="meal-card">
          <div class="meal-image">
            <div class="meal-image">
              <%= image_tag meal.image, alt: meal.name %>
            </div>
          </div>
          <div class="meal-name">
            <p><%= meal.name %></p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/recordings/edit.html.erb
<div class="container-form">

  <div class="form w-50">
      <%= simple_form_for(@recording) do |f| %>
        <h1 class="heading info">Edit Reading</h1>
        <%= f.input :reading, label: 'Reading (mmol/l):', size: "70x5" %>
        <%= f.label :date %>
        <%= f.date_field :date %>
        <%= f.input :time, :collection => ["BB(Before Breakfast)","AB(After Breakfast)" ,"AL(After Lunch)", "AD(After Dinner)"],
        label: 'Meal Type', error: 'Type of Meal is mandatory, please click one', input_html: { maxlength: 200 } %>
        <h1 class="heading">Edit Meal</h1>
        <%= f.input :ingredients, as: :text, input_html: {rows: 50, cols: 100},
        label: 'Meal & Quantity', error: 'Please enter the quanity and details of your meal', input_html: { maxlength: 200 }, class:"meal_input"%>
        <button class="button"><%= f.button :submit, 'Edit' %></button>
      <% end %>


  </div>
    <div class="delete_form">
      <%= link_to "Delete Entry",recording_path(@recording),data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%></button>
    </div>

</div>

app/views/recordings/feedback.html.erb
<div class="container w-50">
  <div class="feedback-heading">
    <h1 class="heading">Feedback</h1>
    <%# <h3 class="heading">Your results are in...</h3> %>
    <h2 class="heading">Your glucose is:</h2>
    <% if @reading < 4.5  %>
      <h3 style="color:blue"><%= @reading %></h3>
    <% elsif @reading >= 4.5 && @reading <= 7.7 %>
      <h3 style="color:green"><%= @reading %></h3>
    <% elsif @reading > 7.7  %>
      <h3 style="color:red"><%= @reading %></h3>
    <% end %>




    <div class="reading">
      <% if @reading > 7.7 %>
        <p>Your value is a bit on the <strong>high</strong> side. Here are some recipes we'd like to recommend, based on your BM input.
      <% elsif @reading >= 4.5 && @reading <= 7.7 %>
        <p>Your value is normal! Well done Mama! Keep up the good work. If you want to have a look at some recipes, here are some that could inspire you!
      <% elsif @reading < 4.5 %>
        <p>Your value is a bit on the <strong>low</strong> side. Here are some recipes we'd like to recommend, based on your BM input.
      <% end %>
    </div>

    <div class="buttons-container">
        <%# <h5><%= link_to "Recipes", meals_path, class: "button" %>
    </div>
  </div>
  <% if @reading > 7.7 %>
    <%= render partial: "recomendation", locals: {timing: @timing_above}  %>
  <% elsif @reading < 4.5 %>
    <%= render partial: "recomendation", locals: {timing: @timing_below}  %>
  <% end %>
</div>

app/views/recordings/index.html.erb
<div class="px-5 mx-5">
<br>
  <h2><%= current_user.first_name %>'s Review</h2>

  <%# Searchbar %>
  <div class="row">
    <div class="col-sm-8 my-3">
      <%= form_tag recordings_path, method: :get, class: "d-flex search-form" do %>
        <div>
          <%= label_tag "query", "Search Date:", class: "mr-2 mt-1" %>
          <%= date_field_tag :query,
                params[:query],
                class: "form-control mr-2",
                style: "width: 200px;",
                placeholder: "YYYY-MM-DD"
            %>
          <%= hidden_field_tag :patient, params[:patient] %>
        </div>

        <%= submit_tag "Search", name: "", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>

  <div class="row m-0">
    <% @searches.each do |search| %>
      <div class="col-12 col-sm-6 col-md-3 mb-3">
        <div class="card">
          <% if search.reading > 7.7 %>
            <div>
              <h6>BM: <strong style="color:red"><%= search.reading %></strong> mmol/L</h6>
            </div>
          <% elsif search.reading >= 4.5 && search.reading <= 7.7 %>
            <h6>BM: <strong style="color:green"><%= search.reading %></strong> mmol/L</h6>
          <% elsif search.reading < 4.5 %>
            <h6>BM: <strong style="color:blue"><%= search.reading %></strong> mmol/L</h6>
          <% end %>
          <h6>Timing: <%= search.time %></h6>
          <h6>Meal details: <%= search.ingredients %></h6>
          <%= link_to "Edit", edit_recording_path(search) %>
          <%= link_to "Delete", recording_path(search), method: :delete, data: { confirm: "Are you sure?" } %>
        </div>
      </div>
    <% end %>
  </div>






  <h1>View your Readings</h1>


  <%# <%= link_to "Add Glucose", new_recording_path, class: "btn btn-flat" %>
  <br>
  <br>
<div class="trends-border">
  <div class="row m-0">
    <% @blood_glucose_recordings.each do |recording| %>
      <div class="col-12 col-sm-6 col-md-3 mb-3">
        <div class="card">
          <% if recording.reading > 7.7 %>
            <div>
              <h6><strong> Glucose: </strong><strong style="color:red"><%= recording.reading %></strong> mmol/L</h6>
              <h6><strong> Date: </strong><%= recording.date.strftime("%d/%m/%Y") %></h6>
              <h6><strong> Time: </strong><%= recording.time %></h6>
              <h6><strong> Meal: </strong> <%= recording.ingredients.truncate(25) %></h6>
            </div>
          <% elsif recording.reading >= 4.5 && recording.reading <= 7.7 %>
            <div>
              <h6><strong> Glucose: </strong><strong style="color:green"><%= recording.reading %></strong> mmol/L</h6>
              <h6><strong> Date: </strong> <%= recording.date %></h6>
              <h6><strong> Time: </strong><%= recording.time %></h6>
              <h6><strong> Meal: </strong><%= recording.ingredients.truncate(25) %></h6>
            </div>
          <% elsif recording.reading < 4.5 %>
            <div>
              <h6><strong> Glucose: </strong><strong style="color:blue"><%= recording.reading %></strong> mmol/L</h6>
              <h6><strong> Date: </strong><%= recording.date %></h6>
              <h6><strong> Time: </strong><%= recording.time %></h6>
              <h6><strong> Meal: </strong><%= recording.ingredients.truncate(25) %></h6>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>
  <%if current_user.clinician? == false %>
    <%= link_to "Back to Dashboard", dashboard_path, class: "btn btn-primary" %>
  <% else %>
    <%= link_to "Back to Dashboard", clinician_dashboard_path, class: "btn btn-primary" %>
  <% end %>
</div>

app/views/recordings/new.html.erb
        <%# <i class="fa-solid fa-droplet"></i> %>
<div class="container-form">

  <div class="form w-50">
      <%= simple_form_for(@recording) do |f| %>
        <h1 class="heading info">New Glucose Reading</h1>
        <h6 class="heading">Input your blood glucose reading and press the 'Add' button to save. </h6>
        <br>
        <%= f.input :reading, label: 'Reading (mmol/l):'%>
        <%= f.label :date %>
        <%= f.date_field :date  %>
        <br>
        <%= f.input :time, :collection => ["BB(Before Breakfast)","AB(After Breakfast)" ,"AL(After Lunch)", "AD(After Dinner)"],
        label: 'When did you take your blood glucose?', error: 'Type of Meal is mandatory, please click one' %>
        <%= f.input :ingredients, as: :text, input_html: {rows: 50, cols: 100},
        label: 'Meal & Quantity (optional)', error: 'Please enter the quanity and details of your meal', input_html: { maxlength: 200 } %>
        <button class="button"><%= f.button :submit, 'Add Glucose' %></button>
      <% end %>



  </div>


</div>