config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get 'recipes/index'
  devise_for :users


  # Homepage
  root to: "pages#home"

  # current_user.clinician? == true ? root to: "pages#clinician_dashboard" :  root to: "pages#home"


  # Meals/Recipe page
  get '/meals/breakfast', to: 'meals#breakfast', as: 'breakfast'
  get '/meals/lunch', to: 'meals#lunch', as: 'lunch'
  get '/meals/snacks', to: 'meals#snacks', as: 'snacks'
  get '/meals/dinner', to: 'meals#dinner', as: 'dinner'
  resources :meals, only: [:index, :show]

   # get '/meals/:id', to: 'meals#show', as: 'meal'




  # User Dashboard
  resources :recordings
  get "dashboard", to: "pages#dashboard"

  # Clinician Dashboard
  get 'clinician_dashboard', to: 'pages#clinician_dashboard'
  get 'dashboard/patients/:id', to: 'pages#show', as: :patient_profile
  # get 'dashboard/patients/:id/chatroom', to: 'pages#show' , as: :chatroom

  get 'recordings/:id/feedback', to: 'recordings#feedback', as: :feedback
  # May get deleted as it gets moved to the dashboard
  get 'recordings/:id', to: 'recordings#new'
  post 'recordings/:id', to: 'recordings#create'
  get 'recordings/:id', to: 'recordings#edit'
  # get 'recordings', to: 'recordings#index', as: :search # This is for the searchbar - get request for items (bloods and meals) that match a certain condition (i.e. the date user input)
  # get 'recordings/:id/edit', to: 'recordings#edit' # Edit your blood glucose entry if user had made a mistake
  patch 'recordings/:id', to: 'recordings#update' # Update your entry, given your details that were previously there( present in the form), to change
  delete 'recordings/:id', to: 'recordings#destroy' # Delete your BM entry


  # Chatroom
  # get 'chatroom/:consultation_id', to: 'chatrooms#index'
  resources :chatrooms, only: [:show] do
    resources :messages , only: [:create]
  end

  # resources :users do
  #   post 'create_chat', on: :member
  #   resources :chatrooms, only: [:index, :show] do
  #     resources :messages, only: [:create]
  #   end
  # end





end

app/views/pages/clinician_dashboard.html.erb
<div class="dashboard-page">
  <h2>Clinician Dashboard</h2>

  <div class="intro">
    <h2>Welcome, <%= current_user.first_name %>!</h2>
    <p>Please see a list of all your patients below:</p>
  </div>

  <div class="mini-profile actions">
    <div>
      <h3>Profile</h3>
      <br>
      <p><strong>Name:</strong> <%= current_user.first_name %> <%= current_user.last_name %></p>
      <p><strong>Status:</strong> <%if current_user.clinician? %><%= "You are a member of staff" %><%end%></p>
    </div>
    <div class="right-side">
      <div class="calendar">
        <h3>Calendar</h3>
        <div class="month">
          <ul>
            <li class="prev">&#10094;</li>
            <li class="next">&#10095;</li>
            <li>May<br><span style="font-size:18px">2024</span></li>
          </ul>
        </div>
        <ul class="weekdays">
          <li>Mo</li>
          <li>Tu</li>
          <li>We</li>
          <li>Th</li>
          <li>Fr</li>
          <li>Sa</li>
          <li>Su</li>
        </ul>
        <ul class="days">
          <li>1</li>
          <li>2</li>
          <li>3</li>
          <li>4</li>
          <li>5</li>
          <li>6</li>
          <li>7</li>
          <li>8</li>
          <li>9</li>
          <li>10</li>
          <li>11</li>
          <li>12</li>
          <li>13</li>
          <li>14</li>
          <li>15</li>
          <li>16</li>
          <li>17</li>
          <li>18</li>
          <li>19</li>
          <li>20</li>
          <li>21</li>
          <li>22</li>
          <li>23</li>
          <li><span class="active">24</span></li>
          <li>25</li>
          <li>26</li>
          <li>27</li>
          <li>28</li>
          <li>29</li>
          <li>30</li>
        </ul>
      </div>
    </div>
  </div>

<div class="actions-doctorp">
  <div class="left-side">
    <div class="current-progress">
      <h3>Patients:</h3>
      <div class="cards">
        <% @patients.each do |patient| %>

          <div class="card">
            <p><strong>Full Name:</strong> <%= patient.first_name %> <%= patient.last_name %></p>
            <p><strong>D.O.B:</strong> <%= patient.birthday.strftime("%B %d, %Y") %></p>
            <p><strong>Due Date:</strong> <%= patient.due_date.strftime("%B %d, %Y") %></p>

              <%# <% current_user.patient_consultations.each do |consultation| %>
              <%# <div style= "background-color: pink; border-radius: 5px; padding: 2px 10px;"><%= link_to "Click to chat with your Patient", chatroom_path(consultation.chatroom)  %>
              <%# <% end %>
              <%= link_to chatroom_path(patient.consultations.last.chatroom) do %>
              <div style="font-size: 30px" class="mx-2">💬</div>

              <% end %>
              <div class="buttons-meals-group">
                <%= link_to "View trend", recordings_path(patient: patient), class: "btn btn-flat" %>
              </div>
          </div>




            <%# <p><%= link_to "See Patient profile", recordings_path(patient: patient) %>

          <% end %>

      </div>
      </div>
    </div>
  </div>
  <%# </div> %>
</div>

<%# User.last.consultations.last.chatroom %>

<%# User.first.consultations.first.chatroom %>

app/views/pages/dashboard.html.erb
<div class="dashboard-page">

<!-- Introduction and Mini-Profile -->
<div class="intro" style="margin: 25px 50px">
  <h2>Welcome, <%= current_user.first_name %>!</h2>
  <br>
  <p>Keeping track of your glucose levels during pregnancy is vital for the well-being of both you and your baby. </p>
  <p>Glucomama  is here to help you.</p>
  </div>
  <div class="mini-profile actions" style="margin: 25px 50px">
      <div class="mini-profile-info" >
        <h3>Profile</h3>
          <br>
        <div class="d-flex">
         <% current_user.consultations.each do |consultation| %>
          <h4><strong>Chat with your clinician: </strong> <%= consultation.clinician.first_name %>  </h4>
          <%= link_to  chatroom_path(consultation.chatroom) do  %>
            <div style="font-size: 30px" class="mx-2">💬</div>
          <% end %>
         <% end %>
        </div>



        <p><strong>Name:</strong> <%= current_user.first_name %></p>
        <p><strong>Birthday:</strong> <%= current_user.birthday.strftime("%B %d, %Y") %></p>
        <p><strong>Due Date:</strong> <%= current_user.due_date.strftime("%B %d, %Y") %></p>




      </div>
        <div class="buttons-dashboard-group">
        <div class="button-container">
          <div class="buttons-dashboard">
            <%= link_to new_recording_path do %>
              <%= image_tag("monitor.png", alt: "input", class: "small-icon btn") %>
              <p class="text-center">Add Glucose</p>
            <% end %>
          </div>
          <div class="buttons-dashboard">
            <%= link_to meals_path do %>
              <%= image_tag("addmeal.png", alt: "input", class: "small-icon btn") %>
              <p class="text-center">Recipes</p>
            <% end %>
          </div>
          <div class="buttons-dashboard">
            <%= link_to recordings_path do %>
              <%= image_tag("trend.png", alt: "input", class: "small-icon btn") %>
              <p class="text-center">View trends</p>
            <% end %>
          </div>
        </div>
      </div>


  </div>


<div class="actions">

  <div class="left-side">
    <!-- Current Progress Widget -->
    <div class="current-progress">
      <h3>Current Progress</h3>
      <% if current_user.recordings.any? %>
        <p><%= "Your current blood glucose level is #{current_user.recordings.last.reading}." %></p>
      <% else %>
        <p><%= "Please log your blood glucose reading to track your progress." %></p>
      <% end %>
    </div>

  <!-- Trends in BM -->
        <div class="trends">
          <h3>Blood Glucose Trends</h3>
          <p><%= "Your blood glucose levels have been stable for the past few days." %></p>
          <% if current_user.recordings.where(created_at: Date.today.prev_day.all_day).any? %>
            <%# <%= image_tag("image.png", alt: "Day before trend", class: "img") %>
          <% else %>
            <p><%= "No recordings found for the day before." %></p>
          <% end %>
        </div>
  </div>
     <!-- Buttons to redirect to Recipe and Glucose Input pages -->
     <div class="right-side">
        <div class="calendar">
            <h3>Calendar</h3>

              <div class="month">
                <ul>
                  <li class="prev">&#10094;</li>
                  <li class="next">&#10095;</li>
                  <li>May<br><span style="font-size:18px">2024</span></li>
                </ul>
              </div>

              <ul class="weekdays">
                <li>Mo</li>
                <li>Tu</li>
                <li>We</li>
                <li>Th</li>
                <li>Fr</li>
                <li>Sa</li>
                <li>Su</li>
              </ul>

              <ul class="days">
                <li>1</li>
                <li>2</li>
                <li>3</li>
                <li>4</li>
                <li>5</li>
                <li>6</li>
                <li>7</li>
                <li>8</li>
                <li>9</li>
                <li>10</li>
                <li>11</li>
                <li>12</li>
                <li>13</li>
                <li>14</li>
                <li>15</li>
                <li>16</li>
                <li>17</li>
                <li>18</li>
                <li>19</li>
                <li>20</li>
                <li>21</li>
                <li>22</li>
                <li>23</li>
                <li><span class="active">24</span>
                <li>25</li>
                <li>26</li>
                <li>27</li>
                <li>28</li>
                <li>29</li>
                <li>30</li>
              </ul>

          </div>
      </div>




  </div>
</div>


<!--
    <div class="buttons">
      <h3>Actions</h3>
      <%# <%= img_to %>
      <%= link_to new_recording_path do %>
        <%= image_tag("Gluco_back.png", alt: "input", class: "small-icon btn") %>
      <% end %>
      <%= link_to meals_path do %>
        <%= image_tag("meals.png", alt: "input", class: "small-icon btn") %>
      <% end %>
      <%= button_to "Explore Recipes", "#", class: "btn" %>
      <%= button_to "View Blood Glucose", "#", class: "btn" %>
    </div>

  </div>
</div>

  <%= link_to "Back to Dashboard", dashboard_path %> -->

app/views/pages/home.html.erb
<div class= "home-banner">
  <div class="container">

    <div class="banner_text">
      <h2>Empowering <span style="color: #FD7973 ">Healthy</span> Choices for You and Baby</h2>
    </div>

    <div class="slogan_text">
      <h3>Stay in control with <span style="color: #FD7973 "><strong>GlucoMama</strong></span>, the ultimate app for managing gestational diabetes</h3>
      <p><%= link_to 'Add Glucose', new_recording_path, class: "btn btn-flat" %></p>

    </div>
  </div>
    <div class="contentDiv">
      <img class="arrow" src="https://cdn3.iconfinder.com/data/icons/google-material-design-icons/48/ic_keyboard_arrow_down_48px-128.png" />
    </div>
</div>


<div class="home-info">
  <div class="container-slogan mb-5" >
    <div class="card-slogan-1">
      <p><strong>About Gestational Diabetes</strong></p>
      <p>Gestational diabetes develops during pregnancy when the body can't produce enough insulin, causing high blood sugar.
        It usually resolves after childbirth but can lead to complications.
        Management involves diet, exercise, sometimes insulin, and regular monitoring.</p>
      <p><%= link_to 'Further info', 'https://www.nhs.uk/conditions/gestational-diabetes/', class: "btn btn-flat" %></p>
    </div>
    <div class="container-slogan-img">
      <%= image_tag("slogan1.png", alt: "gestational_dbm_woman", class: "img_1") %>
    </div>
  </div>

  <div class="container-slogan mb-5" >
    <div class="container-slogan-img">
      <%= image_tag("slogan2.png", alt: "dbm_woman_monitor", class: "img_2") %>
    </div>
    <div class="card-slogan-1">
      <p><strong>Food & Diet</strong></p>
      <p>What you eat during pregnacy can help your baby grow healthy and get the best start in life.
      A healthy diet is recommended for all pregnant women. Thre are some foods that you are advised to avoid during pregnancy,
      and there are other dietry factors to condiser when you have GDM which can affect your blood glucose.</p>
      <p><%= link_to 'Further info', 'https://www.nhs.uk/pregnancy/keeping-well/have-a-healthy-diet/', class: "btn btn-flat" %></p>
    </div>
  </div>

  <div class="container-slogan" >
    <div class="card-slogan-1">
      <p><strong>Activity & Fitness</strong></p>
      <p>Physical activity is recommended as it beifits both you and your baby's health.
      Physical activity can help control blood glucose levels, improve pregnancy outcomes as well as support weight managment.</p>
      <p><%= link_to 'Further info', 'https://www.nhs.uk/pregnancy/keeping-well/exercise/', class: "btn btn-flat" %></p>
    </div>
    <div class="container-slogan-img">
      <%= image_tag("jogmum.png", alt: "gestational_dbm", class: "img_3") %>
    </div>
  </div>
</div>

app/views/pages/show.html.erb
<!-- dashboard.html.erb -->

<div class="row m-0">
  <div class="col-12">
    <!-- Introduction and Mini-Profile -->
    <div class="intro" style="margin: 50px">
      <h2>Welcome, <%= current_user.first_name %>!</h2>
      <p>Tracking your glucose levels during pregnancy is crucial for a healthy you and your baby.</p>

      <% unless current_user.clinician? %>
        <div class="mini-profile" style="margin: 50px">
          <h3>Profile</h3>
          <p><strong>Name:</strong> <%= current_user.first_name %></li></p>
          <p><strong>Date of Birth:</strong> <%= current_user.birthday %> <strong>Due Date:</strong> <%= current_user.due_date %></p>
        </div>
      <% end %>
    </div>

    <% unless current_user.clinician? %>
      <div class="actions">
        <div class="left-side">
          <!-- Current Progress Widget -->
          <div class="current-progress">
            <h3>Current Progress</h3>
            <% if current_user.recordings.any? %>
              <p>Your current blood glucose level is <%= current_user.recordings.last %>.</p>
            <% else %>
              <p>Please log your blood glucose reading to track your progress.</p>
            <% end %>
          </div>

          <!-- Trends in BM -->
          <div class="trends">
            <h3>Blood Glucose Trends</h3>
            <!-- Chart or graph to display trends in BM readings -->
            <%#= chart_data %>
          </div>
        </div>

        <!-- Buttons to redirect to Recipe and Glucose Input pages -->
        <div class="right-side">
          <div class="calendar">
            <h3>Calendar</h3>
            <div class="month">
              <ul>
                <li class="prev">&#10094;</li>
                <li class="next">&#10095;</li>
                <li>May<br><span style="font-size:18px">2024</span></li>
              </ul>
            </div>

            <ul class="weekdays">
              <li>Mo</li>
              <li>Tu</li>
              <li>We</li>
              <li>Th</li>
              <li>Fr</li>
              <li>Sa</li>
              <li>Su</li>
            </ul>

            <ul class="days">
              <li>1</li>
              <li>2</li>
              <li>3</li>
              <li>4</li>
              <li>5</li>
              <li>6</li>
              <li>7</li>
              <li>8</li>
              <li>9</li>
              <li>10</li>
              <li>11</li>
              <li>12</li>
              <li>13</li>
              <li>14</li>
              <li>15</li>
              <li>16</li>
              <li><span class="active">17</span></li>
              <li>18</li>
              <li>19</li>
              <li>20</li>
              <li>21</li>
              <li>22</li>
              <li>23</li>
              <li>24</li>
              <li>25</li>
              <li>26</li>
              <li>27</li>
              <li>28</li>
              <li>29</li>
              <li>30</li>
            </ul>
          </div>

          <div class="buttons">
            <h3>Actions</h3>
            <%= button_to "Explore Recipes", "#", class: "btn" %>
            <%= button_to "Log Blood Glucose", "#", class: "btn" %>
            <%= button_to "View Blood Glucose", "#", class: "btn" %>
          </div>
        </div>
      </div>
    <% else %>
      <!-- This section SHOULD show if the user is a clinician -->
      <h1>See your patients</h1>
      <% @users.each do |u| %>
        <% unless u.clinician? %>
          <div class="patient-card-container" style="border: solid;">
            <h6>Name: <%= u.first_name %></h6>
            <h6>Surname: <%= u.last_name %></h6>
            <h6>D.O.B: <%= u.birthday %></h6>
            <h6>Due Date: <%= u.due_date %></h6>
            <%= link_to "See Profile", user_path(u), class: "btn btn-primary" %>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>
<div class="px-5 mx-5">




  <%# <h1>See all Meals </h1>

  <% @meal_recordings.each do |recording| %>

      <%# <div>
        <strong><h6>Meal:<%=  recording.ingredients </h6></strong>
        <%# <h6>Date:<%=  recording.date </h6>
        <%# <h6>Time:<%=  recording.time </h6>


      </div>
  <% end %>


  <%# <h1>Image here </h1> %>
  <%# <%= line_chart @time.map { |t|
      {name: t.value, data: t.feats.group_by_day(:reading).count}
  } %>

  <%= link_to "Back to Dashboard", dashboard_path %>