config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get 'recipes/index'
  devise_for :users


  # Homepage
  root to: "pages#home"

  # current_user.clinician? == true ? root to: "pages#clinician_dashboard" :  root to: "pages#home"


  # Meals/Recipe page
  get '/meals/breakfast', to: 'meals#breakfast', as: 'breakfast'
  get '/meals/lunch', to: 'meals#lunch', as: 'lunch'
  get '/meals/snacks', to: 'meals#snacks', as: 'snacks'
  get '/meals/dinner', to: 'meals#dinner', as: 'dinner'
  resources :meals, only: [:index, :show]

   # get '/meals/:id', to: 'meals#show', as: 'meal'




  # User Dashboard
  resources :recordings
  get "dashboard", to: "pages#dashboard"

  # Clinician Dashboard
  get 'clinician_dashboard', to: 'pages#clinician_dashboard'
  get 'dashboard/patients/:id', to: 'pages#show', as: :patient_profile
  # get 'dashboard/patients/:id/chatroom', to: 'pages#show' , as: :chatroom

  get 'recordings/:id/feedback', to: 'recordings#feedback', as: :feedback
  # May get deleted as it gets moved to the dashboard
  get 'recordings/:id', to: 'recordings#new'
  post 'recordings/:id', to: 'recordings#create'
  get 'recordings/:id', to: 'recordings#edit'
  # get 'recordings', to: 'recordings#index', as: :search # This is for the searchbar - get request for items (bloods and meals) that match a certain condition (i.e. the date user input)
  # get 'recordings/:id/edit', to: 'recordings#edit' # Edit your blood glucose entry if user had made a mistake
  patch 'recordings/:id', to: 'recordings#update' # Update your entry, given your details that were previously there( present in the form), to change
  delete 'recordings/:id', to: 'recordings#destroy' # Delete your BM entry


  # Chatroom
  # get 'chatroom/:consultation_id', to: 'chatrooms#index'
  resources :chatrooms, only: [:show] do
    resources :messages , only: [:create]
  end

  # resources :users do
  #   post 'create_chat', on: :member
  #   resources :chatrooms, only: [:index, :show] do
  #     resources :messages, only: [:create]
  #   end
  # end





end

app/models/meal.rb
class Meal < ApplicationRecord
  has_many :results
  has_many :recordings, through: :results
  has_one_attached :photo
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  def index
    @meals = Meal.all

  end

  def show
    @meal = Meal.find(params[:id])
  end

  def breakfast
    @meals = Meal.where(timing: "breakfast")
  end

  def lunch
    @meals = Meal.where(timing: "lunch")
  end

  def dinner
    @meals = Meal.where(timing: "dinner")
  end

  def snacks
    @meals = Meal.where(timing: "snack")
  end
end

app/views/meals/breakfast.html.erb
<h1>Breakfast</h1>

<div class="buttons-meals-group">
      <%= link_to "All", meals_path, class: "button-meals-btn" %>
      <%= link_to "Breakfast", breakfast_path, class: "button-meals-btn" %>
      <%= link_to "Lunch", lunch_path, class: "button-meals-btn" %>
      <%= link_to "Snacks", snacks_path, class: "button-meals-btn" %>
      <%= link_to "Dinner", dinner_path, class: "button-meals-btn" %>
</div>


<div class="meal-index-card">
  <div class="meal-cards-container">
    <% @meals.each do |meal| %>
      <div class="meal-card">
      <%= link_to meal_path(meal) do  %>
        <div class="meal-image">
          <%= image_tag meal.image, alt: meal.name %>
        </div>
        <div class="meal-name">
          <p><%= meal.name %></p>
        </div>
         <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/meals/dinner.html.erb
<h1>Dinner</h1>

<div class="buttons-meals-group">
      <%= link_to "All", meals_path, class: "button-meals-btn" %>
      <%= link_to "Breakfast", breakfast_path, class: "button-meals-btn" %>
      <%= link_to "Lunch", lunch_path, class: "button-meals-btn" %>
      <%= link_to "Snacks", snacks_path, class: "button-meals-btn" %>
      <%= link_to "Dinner", dinner_path, class: "button-meals-btn" %>
</div>


<div class="meal-index-card">
  <div class="meal-cards-container">
    <% @meals.each do |meal| %>
      <div class="meal-card">
      <%= link_to meal_path(meal) do  %>
        <div class="meal-image">
          <%= image_tag meal.image, alt: meal.name %>
        </div>
        <div class="meal-name">
          <p><%= meal.name %></p>
        </div>
         <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/meals/index.html.erb
<h1>Meals </h1>
<%# <div class="container">
  <div class=" d-flex justify-content-around" > %>
    <div class="buttons-meals-group">
      <%= link_to "All", meals_path, class: "button-meals-btn" %>
      <%= link_to "Breakfast", breakfast_path, class: "button-meals-btn" %>
      <%= link_to "Lunch", lunch_path, class: "button-meals-btn" %>
      <%= link_to "Snacks", snacks_path, class: "button-meals-btn" %>
      <%= link_to "Dinner", dinner_path, class: "button-meals-btn" %>
    </div>


  <%# </div>
</div> %>

<div class="meal-index-card">
  <div class="meal-cards-container">
    <% @meals.each do |meal| %>
      <div class="meal-card">
      <%= link_to meal_path(meal) do  %>
        <div class="meal-image">
          <%= image_tag meal.image, alt: meal.name %>
        </div>
        <div class="meal-name">
          <p><%= meal.name %></p>
        </div>
         <% end %>
      </div>
    <% end %>
  </div>
</div>




<%# <div class="meal-index-card">
  <div class="meal-cards-container">
    <% [chia_pudding, mushroom_egg, tofu_scramble, spinach_omlette, chicken_veg, vege_salad, lentil_soup, sweet_potato, chicken_salad, salmon_asparagus, tofu_curry, chickpea_stew, apple_almond, greek_yoghurt, cheddar, boiled_egg].each do |meal| %>
      <%# <div class="meal-card">
        <div class="meal-image">
          <%= image_tag meal.image, alt: meal.name %>
        <%# </div>
        <div class="meal-name">
          <p><%= meal.name %>
        <%# </div>
      </div>
    <% end %>
  <%# </div>
</div>    %>

app/views/meals/lunch.html.erb
<h1>Lunch</h1>
<div class="buttons-meals-group">
      <%= link_to "All", meals_path, class: "button-meals-btn" %>
      <%= link_to "Breakfast", breakfast_path, class: "button-meals-btn" %>
      <%= link_to "Lunch", lunch_path, class: "button-meals-btn" %>
      <%= link_to "Snacks", snacks_path, class: "button-meals-btn" %>
      <%= link_to "Dinner", dinner_path, class: "button-meals-btn" %>
</div>


<div class="meal-index-card">
  <div class="meal-cards-container">
    <% @meals.each do |meal| %>
      <div class="meal-card">
      <%= link_to meal_path(meal) do  %>
        <div class="meal-image">
          <%= image_tag meal.image, alt: meal.name %>
        </div>
        <div class="meal-name">
          <p><%= meal.name %></p>
        </div>
         <% end %>
      </div>
    <% end %>
  </div>
</div>
<%# <%= link_to "Back To Meals", meals_path %>
<%# <%= link_to "Back To Meals", meals_path %>

app/views/meals/meal.html.erb
<h1>Show all Meals and Recipes</h1>

app/views/meals/show.html.erb
<h1><%= @meal.name %></h1>

<div class="meal-details">
  <div class="meal-image">
          <%= image_tag @meal.image, alt: @meal.name %>
        </div>
  <p><%= @meal.note %></p>
  <p><strong>Timing:</strong> <%= @meal.timing %></p>
  <p><strong>Recipe:</strong></p>
  <p><%= simple_format(@meal.recipe) %></p>
</div>
  <div class="buttons-meals-group">
      <%= link_to "Recipes", meals_path, class: "button-meals-btn" %>
  </div>

app/views/meals/snacks.html.erb
<h1>Snacks</h1>
<div class="buttons-meals-group">
      <%= link_to "All", meals_path, class: "button-meals-btn" %>
      <%= link_to "Breakfast", breakfast_path, class: "button-meals-btn" %>
      <%= link_to "Lunch", lunch_path, class: "button-meals-btn" %>
      <%= link_to "Snacks", snacks_path, class: "button-meals-btn" %>
      <%= link_to "Dinner", dinner_path, class: "button-meals-btn" %>
</div>

<div class="meal-index-card">
  <div class="meal-cards-container">
    <% @meals.each do |meal| %>
      <div class="meal-card">
      <%= link_to meal_path(meal) do  %>
        <div class="meal-image">
          <%= image_tag meal.image, alt: meal.name %>
        </div>
        <div class="meal-name">
          <p><%= meal.name %></p>
        </div>
         <% end %>
      </div>
    <% end %>
  </div>
</div>
<%# <%= link_to "Back To Meals", meals_path %>